### ISSUE TITLE
I couldn't run at AWS with ami 

### ISSUE THREAD

**Issue by kotamat** [graphific/DeepDreamVideo#55]
I follow this site's flow and git clone this
https://github.com/graphific/dl-machine

and run this code

```
bash install_caffe.sh
```

and install protobuf-2.5.0
and set bashrc like this

```
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/leveldb:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/hdf5/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-7.0/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
```

and cloned this repo
https://github.com/graphific/DeepDreamVideo

after that I attempt run `1_movie2frames.sh`
and I'm trying to run

```
python 2_dreaming_time.py -i frames_directory -o processed_frames_dir --gpu 0 -it jpg
```

but kind of this error occurred

```
...
I0902 18:58:02.698053  1641 upgrade_proto.cpp:626] Successfully upgraded file specified using deprecated V1LayerParameter
Traceback (most recent call last):
  File "2_dreaming_time.py", line 507, in <module>
    main(args.input, args.output, args.image_type, args.gpu, args.model_path, args.model_name, args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers, args.guide_image, args.start_frame, args.end_frame, args.verbose)
  File "2_dreaming_time.py", line 309, in main
    frame = np.float32(PIL.Image.open(input + '/%08d.%s' % (frame_i, image_type) ))
TypeError: float() argument must be a string or a number
```

could you tell me solve this probrem if you know? thx!

**Comment by graphific** [comment]
seems you dont have images in your _frames_directory_ ordered by %08d, so decimal numbers of length 8, ie starting with 00000001.png

**Comment by kotamat** [comment]
thank you for your reply.

i guess there are kind of those files..
```
(venv)ubuntu@ip-172-31-5-8:~/DeepDreamVideo$ ls -1 frames_directory/
00000001.jpg
00000002.jpg
00000003.jpg
00000004.jpg
00000005.jpg
00000006.jpg
```

**Comment by kotamat** [comment]
and I tried debugging
```
    if verbose == 3:
        from IPython.display import clear_output, Image, display
        print("display turned on")
+   f = open('text.txt', 'w')
+   f.write(str(PIL.Image.open(input + '/%08d.%s' % (frame_i, image_type) )))
+   f.close()
    frame = np.float32(PIL.Image.open(input + '/%08d.%s' % (frame_i, image_type) ))
    if preview is not 0:
        frame = np.float32(resizePicture(input + '/%08d.%s' % (frame_i, image_type), preview))
```

```
(venv)ubuntu@ip-172-31-5-8:~/DeepDreamVideo$ cat text.txt
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1920x1080 at 0x7F55F1754450>
```

**Comment by davialexandre** [comment]
Got stuck at this same error :(

**Comment by graphific** [comment]
try to add:
print('input + '/%08d.%s' % (frame_i, image_type))
or change the fwrite to: f.write(str(input + '/%08d.%s' % (frame_i, image_type) ))
whats the output?
