### ISSUE TITLE
Protobuf error on certain models

### ISSUE THREAD

**Issue by muchogrande** [graphific/DeepDreamVideo#57]
Got everything working and successfully processed some test images using the googlenet_places205 model, but I am having strange issues when selecting other models. Selecting BLVC_googlenet throws this error: 

Traceback (most recent call last):
  File "2_dreaming_time.py", line 322, in <module>
    args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers)
  File "2_dreaming_time.py", line 151, in main
    text_format.Merge(open(net_fn).read(), model)
  File "/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages/google/protobuf/text_format.py", line 265, in Merge
    return MergeLines(text.split('\n'), message)
  File "/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages/google/protobuf/text_format.py", line 298, in MergeLines
    _ParseOrMerge(lines, message, True)
  File "/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages/google/protobuf/text_format.py", line 229, in _ParseOrMerge
    _MergeField(tokenizer, message, allow_multiple_scalars)
  File "/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages/google/protobuf/text_format.py", line 338, in _MergeField
    name = tokenizer.ConsumeIdentifier()
  File "/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages/google/protobuf/text_format.py", line 557, in ConsumeIdentifier
    raise self._ParseError('Expected identifier.')
google.protobuf.text_format.ParseError: 4:1 : Expected identifier.

**Comment by muchogrande** [comment]
Installed the model via terminal and is working fine!
