### ISSUE TITLE
Rollaxis error: numpy version?

### ISSUE THREAD

**Issue by rdooley** [graphific/DeepDreamVideo#60]
Running this on debian jessie after a caffe install I get

```
Processing frame #1
Traceback (most recent call last):
  File "2_dreaming_time.py", line 506, in <module>
    main(args.input, args.output, args.image_type, args.gpu, args.model_path, args.model_name, args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers, args.guide_image, args.start_frame, args.end_frame, args.verbose)
  File "2_dreaming_time.py", line 331, in main
    frame = deepdream(net, frame, image_type=image_type, verbose=verbose, iter_n = iterations, step_size = stepsize, octave_n = octaves, octave_scale = octave_scale, jitter=jitter, end = endparam)
  File "2_dreaming_time.py", line 113, in deepdream
    octaves = [preprocess(net, base_img)]
  File "2_dreaming_time.py", line 39, in preprocess
    return np.float32(np.rollaxis(img, 2)[::-1]) - net.transformer.mean['data']
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1342, in rollaxis
    raise ValueError(msg % ('axis', axis, n))
ValueError: rollaxis: axis (2) must be >=0 and < 2
```

And altering the axis to be either 0 or 1 results in an image match error (image ends up rotated incorrectly).

```
Frame 1 of 122
Frame Time: 23s
Estimated Total Time Remaining: 2783s (0:46:23)
***************************************
Traceback (most recent call last):
  File "2_dreaming_time.py", line 506, in <module>
    main(args.input, args.output, args.image_type, args.gpu, args.model_path, args.model_name, args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom, args.stepsize, args.blend, args.layers, args.guide_image, args.start_frame, args.end_frame, args.verbose)
  File "2_dreaming_time.py", line 375, in main
    frame = morphPicture(saveframe,newframe,blendval,preview)
  File "2_dreaming_time.py", line 234, in morphPicture
    return PIL.Image.blend(img1, img2, blend)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2329, in blend
    return im1._new(core.blend(im1.im, im2.im, alpha))
ValueError: images do not match
```

Any help would be appreciated.

numpy version is '1.8.2'

**Comment by rdooley** [comment]
Well this was a conversion of png issue that I have solved.
